
import { Document, DocumentTemplate, Signer, DocumentField, Notification } from '@/contexts/DocumentContext';

export const generateDemoData = () => {
  const demoSigners: Omit<Signer, 'id'>[] = [
    {
      name: 'John Smith',
      email: 'john.smith@company.com',
      role: 'signer',
      status: 'signed',
      order: 1,
      canDelegate: true,
      requireAuth: 'email',
      signedAt: new Date('2024-05-20T10:30:00Z'),
    },
    {
      name: 'Sarah Johnson',
      email: 'sarah.johnson@client.com',
      role: 'signer',
      status: 'pending',
      order: 2,
      canDelegate: false,
      requireAuth: 'sms',
    },
    {
      name: 'Mike Davis',
      email: 'mike.davis@legal.com',
      role: 'approver',
      status: 'pending',
      order: 3,
      canDelegate: true,
      requireAuth: 'knowledge',
    },
    {
      name: 'Lisa Chen',
      email: 'lisa.chen@hr.com',
      role: 'cc',
      status: 'pending',
      order: 4,
      canDelegate: false,
      requireAuth: 'none',
    },
  ];

  const demoFields: Omit<DocumentField, 'id'>[] = [
    {
      type: 'signature',
      x: 15,
      y: 20,
      width: 20,
      height: 8,
      page: 1,
      required: true,
      label: 'Employee Signature',
      signerId: 'signer_1',
    },
    {
      type: 'text',
      x: 10,
      y: 35,
      width: 25,
      height: 5,
      page: 1,
      required: true,
      label: 'Full Name',
      value: 'John Smith',
      validation: {
        type: 'custom',
        pattern: '^[A-Za-z\\s]+$',
        message: 'Please enter a valid name',
      },
    },
    {
      type: 'date',
      x: 45,
      y: 35,
      width: 15,
      height: 5,
      page: 1,
      required: true,
      label: 'Date of Birth',
      validation: {
        type: 'custom',
        pattern: '^\\d{2}/\\d{2}/\\d{4}$',
        message: 'Please enter date in MM/DD/YYYY format',
      },
    },
    {
      type: 'checkbox',
      x: 10,
      y: 50,
      width: 5,
      height: 5,
      page: 1,
      required: true,
      label: 'I agree to terms and conditions',
      value: 'true',
    },
    {
      type: 'dropdown',
      x: 10,
      y: 65,
      width: 20,
      height: 5,
      page: 1,
      required: true,
      label: 'Department',
      options: ['Engineering', 'Marketing', 'Sales', 'HR', 'Finance'],
      value: 'Engineering',
    },
    {
      type: 'radio',
      x: 40,
      y: 65,
      width: 25,
      height: 10,
      page: 1,
      required: true,
      label: 'Employment Type',
      options: ['Full-time', 'Part-time', 'Contract', 'Intern'],
      value: 'Full-time',
    },
  ];

  const demoDocuments: Document[] = [
    {
      id: 'doc_1',
      title: 'Employment Agreement - John Smith',
      content: 'JVBERi0xLjQKJcfsj6IKNSAwIG9iago8PAovTGVuZ3RoIDY2CgovRmlsdGVyIC9GbGF0ZURlY29kZQo+PgpzdHJlYW0KeJxNjjEOwjAMRe+SuoNtpU3SHoABiRGJgbKgDlRV751kYOCN773v5xgvNjPEXMh2jlmpJxYjFSGh2wAz3HG5X5Jqu4h2XzSQfOTqfRYgaslUqKQp8Xv2C2lX1DaR4eIzNmPIldnCxUeNmjgBCYRAEBERU+gq7uIrCRMfcNT9VFd3S2YEF2CQnQ==endstream',
      fields: demoFields.map((field, index) => ({
        ...field,
        id: `field_${index + 1}`,
        signerId: index === 0 ? 'signer_1' : undefined,
      })),
      signers: demoSigners.map((signer, index) => ({
        ...signer,
        id: `signer_${index + 1}`,
      })),
      status: 'sent',
      createdAt: new Date('2024-05-15T09:00:00Z'),
      updatedAt: new Date('2024-05-20T15:30:00Z'),
      signingOrder: 'sequential',
      auditTrail: [
        {
          id: 'audit_1',
          timestamp: new Date('2024-05-15T09:00:00Z'),
          action: 'Document Created',
          actor: 'System',
          details: 'Employment Agreement created',
        },
        {
          id: 'audit_2',
          timestamp: new Date('2024-05-15T09:30:00Z'),
          action: 'Document Sent',
          actor: 'HR Manager',
          details: 'Sent to John Smith for signing',
        },
        {
          id: 'audit_3',
          timestamp: new Date('2024-05-20T10:30:00Z'),
          action: 'Document Signed',
          actor: 'John Smith',
          ipAddress: '192.168.1.100',
          details: 'Document signed by John Smith',
        },
      ],
      reminderSchedule: {
        enabled: true,
        frequency: 'weekly',
        lastSent: new Date('2024-05-18T10:00:00Z'),
        customMessage: 'Please complete your employment agreement signature.',
      },
      expiresAt: new Date('2024-06-15T23:59:59Z'),
      security: {
        requireAuth: true,
        allowPrinting: false,
        allowDownload: true,
      },
      notifications: {
        sendCopyToSender: true,
        ccEmails: ['hr@company.com'],
      },
    },
    {
      id: 'doc_2',
      title: 'NDA - Client Partnership',
      content: 'JVBERi0xLjQKJcfsj6IKNSAwIG9iago8PAovTGVuZ3RoIDY2CgovRmlsdGVyIC9GbGF0ZURlY29kZQo+PgpzdHJlYW0KeJxNjjEOwjAMRe+SuoNtpU3SHoABiRGJgbKgDlRV751kYOCN773v5xgvNjPEXMh2jlmpJxYjFSGh2wAz3HG5X5Jqu4h2XzSQfOTqfRYgaslUqKQp8Xv2C2lX1DaR4eIzNmPIldnCxUeNmjgBCYRAEBERU+gq7uIrCRMfcNT9VFd3S2YEF2CQnQ==endstream',
      fields: [
        {
          id: 'field_nda_1',
          type: 'signature',
          x: 15,
          y: 80,
          width: 20,
          height: 8,
          page: 1,
          required: true,
          label: 'Company Representative',
          signerId: 'signer_nda_1',
        },
        {
          id: 'field_nda_2',
          type: 'signature',
          x: 55,
          y: 80,
          width: 20,
          height: 8,
          page: 1,
          required: true,
          label: 'Client Representative',
          signerId: 'signer_nda_2',
        },
      ],
      signers: [
        {
          id: 'signer_nda_1',
          name: 'Robert Wilson',
          email: 'robert.wilson@company.com',
          role: 'signer',
          status: 'signed',
          order: 1,
          canDelegate: true,
          requireAuth: 'email',
          signedAt: new Date('2024-05-22T14:20:00Z'),
        },
        {
          id: 'signer_nda_2',
          name: 'Jennifer Brown',
          email: 'jennifer.brown@client.com',
          role: 'signer',
          status: 'pending',
          order: 2,
          canDelegate: false,
          requireAuth: 'sms',
        },
      ],
      status: 'sent',
      createdAt: new Date('2024-05-20T11:00:00Z'),
      updatedAt: new Date('2024-05-22T14:20:00Z'),
      signingOrder: 'parallel',
      auditTrail: [],
      expiresAt: new Date('2024-06-20T23:59:59Z'),
    },
    {
      id: 'doc_3',
      title: 'Vendor Service Agreement',
      content: 'JVBERi0xLjQKJcfsj6IKNSAwIG9iago8PAovTGVuZ3RoIDY2CgovRmlsdGVyIC9GbGF0ZURlY29kZQo+PgpzdHJlYW0KeJxNjjEOwjAMRe+SuoNtpU3SHoABiRGJgbKgDlRV751kYOCN773v5xgvNjPEXMh2jlmpJxYjFSGh2wAz3HG5X5Jqu4h2XzSQfOTqfRYgaslUqKQp8Xv2C2lX1DaR4eIzNmPIldnCxUeNmjgBCYRAEBERU+gq7uIrCRMfcNT9VFd3S2YEF2CQnQ==endstream',
      fields: [],
      signers: [],
      status: 'draft',
      createdAt: new Date('2024-05-23T16:45:00Z'),
      updatedAt: new Date('2024-05-23T16:45:00Z'),
      signingOrder: 'sequential',
      auditTrail: [],
    },
    {
      id: 'doc_4',
      title: 'Partnership Agreement - Completed',
      content: 'JVBERi0xLjQKJcfsj6IKNSAwIG9iago8PAovTGVuZ3RoIDY2CgovRmlsdGVyIC9GbGF0ZURlY29kZQo+PgpzdHJlYW0KeJxNjjEOwjAMRe+SuoNtpU3SHoABiRGJgbKgDlRV751kYOCN773v5xgvNjPEXMh2jlmpJxYjFSGh2wAz3HG5X5Jqu4h2XzSQfOTqfRYgaslUqKQp8Xv2C2lX1DaR4eIzNmPIldnCxUeNmjgBCYRAEBERU+gq7uIrCRMfcNT9VFd3S2YEF2CQnQ==endstream',
      fields: [],
      signers: [
        {
          id: 'signer_complete_1',
          name: 'Mark Thompson',
          email: 'mark.thompson@partner.com',
          role: 'signer',
          status: 'signed',
          order: 1,
          canDelegate: false,
          requireAuth: 'email',
          signedAt: new Date('2024-05-10T12:00:00Z'),
        },
        {
          id: 'signer_complete_2',
          name: 'Amanda Foster',
          email: 'amanda.foster@company.com',
          role: 'signer',
          status: 'signed',
          order: 2,
          canDelegate: false,
          requireAuth: 'email',
          signedAt: new Date('2024-05-11T09:30:00Z'),
        },
      ],
      status: 'completed',
      createdAt: new Date('2024-05-08T14:00:00Z'),
      updatedAt: new Date('2024-05-11T09:30:00Z'),
      completedAt: new Date('2024-05-11T09:30:00Z'),
      signingOrder: 'sequential',
      auditTrail: [],
    },
  ];

  const demoTemplates: DocumentTemplate[] = [
    {
      id: 'template_1',
      title: 'Employment Agreement Template',
      name: 'Employment Agreement Template',
      description: 'Standard employment agreement for new hires',
      content: 'JVBERi0xLjQKJcfsj6IKNSAwIG9iago8PAovTGVuZ3RoIDY2CgovRmlsdGVyIC9GbGF0ZURlY29kZQo+PgpzdHJlYW0KeJxNjjEOwjAMRe+SuoNtpU3SHoABiRGJgbKgDlRV751kYOCN773v5xgvNjPEXMh2jlmpJxYjFSGh2wAz3HG5X5Jqu4h2XzSQfOTqfRYgaslUqKQp8Xv2C2lX1DaR4eIzNmPIldnCxUeNmjgBCYRAEBERU+gq7uIrCRMfcNT9VFd3S2YEF2CQnQ==endstream',
      fields: demoFields.map((field, index) => ({
        ...field,
        id: `template_field_${index + 1}`,
      })),
      signers: [
        {
          id: 'template_signer_1',
          name: 'Employee',
          email: '',
          role: 'signer',
          status: 'pending',
          order: 1,
          canDelegate: false,
          requireAuth: 'email',
        },
        {
          id: 'template_signer_2',
          name: 'HR Representative',
          email: 'hr@company.com',
          role: 'signer',
          status: 'pending',
          order: 2,
          canDelegate: true,
          requireAuth: 'email',
        },
      ],
      createdAt: new Date('2024-04-01T10:00:00Z'),
      updatedAt: new Date('2024-05-01T10:00:00Z'),
      category: 'HR',
      tags: ['employment', 'onboarding', 'legal'],
      isPublic: false,
      usageCount: 15,
    },
    {
      id: 'template_2',
      title: 'NDA Template',
      name: 'NDA Template',
      description: 'Non-disclosure agreement for clients and partners',
      content: 'JVBERi0xLjQKJcfsj6IKNSAwIG9iago8PAovTGVuZ3RoIDY2CgovRmlsdGVyIC9GbGF0ZURlY29kZQo+PgpzdHJlYW0KeJxNjjEOwjAMRe+SuoNtpU3SHoABiRGJgbKgDlRV751kYOCN773v5xgvNjPEXMh2jlmpJxYjFSGh2wAz3HG5X5Jqu4h2XzSQfOTqfRYgaslUqKQp8Xv2C2lX1DaR4eIzNmPIldnCxUeNmjgBCYRAEBERU+gq7uIrCRMfcNT9VFd3S2YEF2CQnQ==endstream',
      fields: [
        {
          id: 'template_nda_field_1',
          type: 'signature',
          x: 15,
          y: 80,
          width: 20,
          height: 8,
          page: 1,
          required: true,
          label: 'Party A Signature',
        },
        {
          id: 'template_nda_field_2',
          type: 'signature',
          x: 55,
          y: 80,
          width: 20,
          height: 8,
          page: 1,
          required: true,
          label: 'Party B Signature',
        },
      ],
      signers: [
        {
          id: 'template_nda_signer_1',
          name: 'Company Representative',
          email: '',
          role: 'signer',
          status: 'pending',
          order: 1,
          canDelegate: true,
          requireAuth: 'email',
        },
        {
          id: 'template_nda_signer_2',
          name: 'External Party',
          email: '',
          role: 'signer',
          status: 'pending',
          order: 2,
          canDelegate: false,
          requireAuth: 'sms',
        },
      ],
      createdAt: new Date('2024-03-15T14:30:00Z'),
      updatedAt: new Date('2024-05-15T14:30:00Z'),
      category: 'Legal',
      tags: ['confidentiality', 'legal', 'partnership'],
      isPublic: true,
      usageCount: 8,
    },
  ];

  const demoNotifications: Notification[] = [
    {
      id: 'notif_1',
      documentId: 'doc_1',
      type: 'reminder',
      title: 'Reminder Sent',
      message: 'Reminder sent to Sarah Johnson',
      recipientEmail: 'sarah.johnson@client.com',
      sentAt: new Date('2024-05-21T10:00:00Z'),
      timestamp: new Date('2024-05-21T10:00:00Z'),
      read: false,
      status: 'delivered',
    },
    {
      id: 'notif_2',
      documentId: 'doc_2',
      type: 'info',
      title: 'Document Completed',
      message: 'Document has been completed by all parties',
      recipientEmail: 'jennifer.brown@client.com',
      sentAt: new Date('2024-05-22T14:25:00Z'),
      timestamp: new Date('2024-05-22T14:25:00Z'),
      read: false,
      status: 'delivered',
    },
  ];

  return {
    documents: demoDocuments,
    templates: demoTemplates,
    notifications: demoNotifications,
  };
};
