import { DocumentTemplate } from '@/contexts/DocumentContext';

export const defaultTemplates: DocumentTemplate[] = [
  {
    id: 'template-employment-contract',
    name: 'Employment Contract',
    description: 'Comprehensive employment agreement with standard terms and conditions',
    category: 'Legal',
    tags: ['employment', 'contract', 'legal'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'emp-name', 
        type: 'text', 
        label: 'Employee Name', 
        required: true, 
        x: 100, 
        y: 200, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 200 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'emp-position', 
        type: 'text', 
        label: 'Position', 
        required: true, 
        x: 100, 
        y: 250, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 250 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'start-date', 
        type: 'date', 
        label: 'Start Date', 
        required: true, 
        x: 100, 
        y: 300, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 300 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'salary', 
        type: 'text', 
        label: 'Annual Salary', 
        required: true, 
        x: 100, 
        y: 350, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 350 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'emp-signature', 
        type: 'signature', 
        label: 'Employee Signature', 
        required: true, 
        x: 100, 
        y: 450, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 450 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'employee'
      },
      { 
        id: 'emp-date', 
        type: 'date', 
        label: 'Date Signed', 
        required: true, 
        x: 320, 
        y: 480, 
        width: 100, 
        height: 30,
        position: { x: 320, y: 480 },
        size: { width: 100, height: 30 },
        page: 1
      }
    ],
    signers: [
      { id: 'employee', name: 'Employee', email: '', role: 'employee', order: 1, status: 'pending' },
      { id: 'hr-manager', name: 'HR Manager', email: '', role: 'hr', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-nda',
    name: 'Non-Disclosure Agreement',
    description: 'Standard NDA for protecting confidential information',
    category: 'Legal',
    tags: ['nda', 'confidentiality', 'legal'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'party1-name', 
        type: 'text', 
        label: 'Disclosing Party', 
        required: true, 
        x: 100, 
        y: 180, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 180 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'party2-name', 
        type: 'text', 
        label: 'Receiving Party', 
        required: true, 
        x: 100, 
        y: 220, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 220 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'effective-date', 
        type: 'date', 
        label: 'Effective Date', 
        required: true, 
        x: 100, 
        y: 260, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 260 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'party1-signature', 
        type: 'signature', 
        label: 'Disclosing Party Signature', 
        required: true, 
        x: 100, 
        y: 400, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 400 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'disclosing'
      },
      { 
        id: 'party2-signature', 
        type: 'signature', 
        label: 'Receiving Party Signature', 
        required: true, 
        x: 350, 
        y: 400, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 400 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'receiving'
      }
    ],
    signers: [
      { id: 'disclosing', name: 'Disclosing Party', email: '', role: 'party1', order: 1, status: 'pending' },
      { id: 'receiving', name: 'Receiving Party', email: '', role: 'party2', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-lease-agreement',
    name: 'Residential Lease Agreement',
    description: 'Standard residential property lease agreement',
    category: 'Real Estate',
    tags: ['lease', 'rental', 'property'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'tenant-name', 
        type: 'text', 
        label: 'Tenant Name', 
        required: true, 
        x: 100, 
        y: 150, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 150 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'landlord-name', 
        type: 'text', 
        label: 'Landlord Name', 
        required: true, 
        x: 100, 
        y: 190, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 190 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'property-address', 
        type: 'text', 
        label: 'Property Address', 
        required: true, 
        x: 100, 
        y: 230, 
        width: 300, 
        height: 30,
        position: { x: 100, y: 230 },
        size: { width: 300, height: 30 },
        page: 1
      },
      { 
        id: 'monthly-rent', 
        type: 'text', 
        label: 'Monthly Rent', 
        required: true, 
        x: 100, 
        y: 270, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 270 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'lease-term', 
        type: 'text', 
        label: 'Lease Term', 
        required: true, 
        x: 100, 
        y: 310, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 310 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'tenant-signature', 
        type: 'signature', 
        label: 'Tenant Signature', 
        required: true, 
        x: 100, 
        y: 450, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 450 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'tenant'
      },
      { 
        id: 'landlord-signature', 
        type: 'signature', 
        label: 'Landlord Signature', 
        required: true, 
        x: 350, 
        y: 450, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 450 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'landlord'
      }
    ],
    signers: [
      { id: 'tenant', name: 'Tenant', email: '', role: 'tenant', order: 1, status: 'pending' },
      { id: 'landlord', name: 'Landlord', email: '', role: 'landlord', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-purchase-agreement',
    name: 'Purchase Agreement',
    description: 'General purchase agreement for goods or services',
    category: 'Commercial',
    tags: ['purchase', 'agreement', 'commercial'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'buyer-name', 
        type: 'text', 
        label: 'Buyer Name', 
        required: true, 
        x: 100, 
        y: 160, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 160 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'seller-name', 
        type: 'text', 
        label: 'Seller Name', 
        required: true, 
        x: 100, 
        y: 200, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 200 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'item-description', 
        type: 'text', 
        label: 'Item Description', 
        required: true, 
        x: 100, 
        y: 240, 
        width: 300, 
        height: 30,
        position: { x: 100, y: 240 },
        size: { width: 300, height: 30 },
        page: 1
      },
      { 
        id: 'purchase-price', 
        type: 'text', 
        label: 'Purchase Price', 
        required: true, 
        x: 100, 
        y: 280, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 280 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'delivery-date', 
        type: 'date', 
        label: 'Delivery Date', 
        required: true, 
        x: 100, 
        y: 320, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 320 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'buyer-signature', 
        type: 'signature', 
        label: 'Buyer Signature', 
        required: true, 
        x: 100, 
        y: 420, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 420 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'buyer'
      },
      { 
        id: 'seller-signature', 
        type: 'signature', 
        label: 'Seller Signature', 
        required: true, 
        x: 350, 
        y: 420, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 420 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'seller'
      }
    ],
    signers: [
      { id: 'buyer', name: 'Buyer', email: '', role: 'buyer', order: 1, status: 'pending' },
      { id: 'seller', name: 'Seller', email: '', role: 'seller', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-service-agreement',
    name: 'Service Agreement',
    description: 'Professional service agreement with terms and conditions',
    category: 'Commercial',
    tags: ['service', 'agreement', 'professional'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'client-name', 
        type: 'text', 
        label: 'Client Name', 
        required: true, 
        x: 100, 
        y: 170, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 170 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'provider-name', 
        type: 'text', 
        label: 'Service Provider', 
        required: true, 
        x: 100, 
        y: 210, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 210 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'service-description', 
        type: 'text', 
        label: 'Service Description', 
        required: true, 
        x: 100, 
        y: 250, 
        width: 300, 
        height: 30,
        position: { x: 100, y: 250 },
        size: { width: 300, height: 30 },
        page: 1
      },
      { 
        id: 'service-fee', 
        type: 'text', 
        label: 'Service Fee', 
        required: true, 
        x: 100, 
        y: 290, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 290 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'start-date', 
        type: 'date', 
        label: 'Start Date', 
        required: true, 
        x: 100, 
        y: 330, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 330 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'client-signature', 
        type: 'signature', 
        label: 'Client Signature', 
        required: true, 
        x: 100, 
        y: 430, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 430 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'client'
      },
      { 
        id: 'provider-signature', 
        type: 'signature', 
        label: 'Provider Signature', 
        required: true, 
        x: 350, 
        y: 430, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 430 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'provider'
      }
    ],
    signers: [
      { id: 'client', name: 'Client', email: '', role: 'client', order: 1, status: 'pending' },
      { id: 'provider', name: 'Service Provider', email: '', role: 'provider', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-consulting-agreement',
    name: 'Consulting Agreement',
    description: 'Professional consulting services agreement with project scope and deliverables',
    category: 'Professional Services',
    tags: ['consulting', 'professional', 'services'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'consultant-name', 
        type: 'text', 
        label: 'Consultant Name', 
        required: true, 
        x: 100, 
        y: 160, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 160 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'client-company', 
        type: 'text', 
        label: 'Client Company', 
        required: true, 
        x: 100, 
        y: 200, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 200 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'project-scope', 
        type: 'text', 
        label: 'Project Scope', 
        required: true, 
        x: 100, 
        y: 240, 
        width: 350, 
        height: 30,
        position: { x: 100, y: 240 },
        size: { width: 350, height: 30 },
        page: 1
      },
      { 
        id: 'hourly-rate', 
        type: 'text', 
        label: 'Hourly Rate', 
        required: true, 
        x: 100, 
        y: 280, 
        width: 120, 
        height: 30,
        position: { x: 100, y: 280 },
        size: { width: 120, height: 30 },
        page: 1
      },
      { 
        id: 'project-duration', 
        type: 'text', 
        label: 'Project Duration', 
        required: true, 
        x: 240, 
        y: 280, 
        width: 150, 
        height: 30,
        position: { x: 240, y: 280 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'consultant-signature', 
        type: 'signature', 
        label: 'Consultant Signature', 
        required: true, 
        x: 100, 
        y: 380, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 380 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'consultant'
      },
      { 
        id: 'client-signature', 
        type: 'signature', 
        label: 'Client Signature', 
        required: true, 
        x: 350, 
        y: 380, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 380 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'client'
      }
    ],
    signers: [
      { id: 'consultant', name: 'Consultant', email: '', role: 'consultant', order: 1, status: 'pending' },
      { id: 'client', name: 'Client', email: '', role: 'client', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-partnership-agreement',
    name: 'Partnership Agreement',
    description: 'Business partnership agreement outlining roles, responsibilities, and profit sharing',
    category: 'Corporate',
    tags: ['partnership', 'business', 'corporate'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'partner1-name', 
        type: 'text', 
        label: 'Partner 1 Name', 
        required: true, 
        x: 100, 
        y: 150, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 150 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'partner2-name', 
        type: 'text', 
        label: 'Partner 2 Name', 
        required: true, 
        x: 100, 
        y: 190, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 190 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'business-name', 
        type: 'text', 
        label: 'Business Name', 
        required: true, 
        x: 100, 
        y: 230, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 230 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'partner1-percentage', 
        type: 'text', 
        label: 'Partner 1 Ownership %', 
        required: true, 
        x: 100, 
        y: 270, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 270 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'partner2-percentage', 
        type: 'text', 
        label: 'Partner 2 Ownership %', 
        required: true, 
        x: 270, 
        y: 270, 
        width: 150, 
        height: 30,
        position: { x: 270, y: 270 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'effective-date', 
        type: 'date', 
        label: 'Effective Date', 
        required: true, 
        x: 100, 
        y: 310, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 310 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'partner1-signature', 
        type: 'signature', 
        label: 'Partner 1 Signature', 
        required: true, 
        x: 100, 
        y: 400, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 400 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'partner1'
      },
      { 
        id: 'partner2-signature', 
        type: 'signature', 
        label: 'Partner 2 Signature', 
        required: true, 
        x: 350, 
        y: 400, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 400 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'partner2'
      }
    ],
    signers: [
      { id: 'partner1', name: 'Partner 1', email: '', role: 'partner', order: 1, status: 'pending' },
      { id: 'partner2', name: 'Partner 2', email: '', role: 'partner', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-vendor-agreement',
    name: 'Vendor Agreement',
    description: 'Standard vendor/supplier agreement for goods and services procurement',
    category: 'Procurement',
    tags: ['vendor', 'supplier', 'procurement'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'vendor-company', 
        type: 'text', 
        label: 'Vendor Company', 
        required: true, 
        x: 100, 
        y: 150, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 150 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'client-company', 
        type: 'text', 
        label: 'Client Company', 
        required: true, 
        x: 100, 
        y: 190, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 190 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'services-description', 
        type: 'text', 
        label: 'Services/Products Description', 
        required: true, 
        x: 100, 
        y: 230, 
        width: 350, 
        height: 30,
        position: { x: 100, y: 230 },
        size: { width: 350, height: 30 },
        page: 1
      },
      { 
        id: 'contract-value', 
        type: 'text', 
        label: 'Contract Value', 
        required: true, 
        x: 100, 
        y: 270, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 270 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'payment-terms', 
        type: 'text', 
        label: 'Payment Terms', 
        required: true, 
        x: 270, 
        y: 270, 
        width: 180, 
        height: 30,
        position: { x: 270, y: 270 },
        size: { width: 180, height: 30 },
        page: 1
      },
      { 
        id: 'contract-duration', 
        type: 'text', 
        label: 'Contract Duration', 
        required: true, 
        x: 100, 
        y: 310, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 310 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'vendor-signature', 
        type: 'signature', 
        label: 'Vendor Signature', 
        required: true, 
        x: 100, 
        y: 400, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 400 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'vendor'
      },
      { 
        id: 'client-signature', 
        type: 'signature', 
        label: 'Client Signature', 
        required: true, 
        x: 350, 
        y: 400, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 400 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'client'
      }
    ],
    signers: [
      { id: 'vendor', name: 'Vendor', email: '', role: 'vendor', order: 1, status: 'pending' },
      { id: 'client', name: 'Client', email: '', role: 'client', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-loan-agreement',
    name: 'Loan Agreement',
    description: 'Personal or business loan agreement with repayment terms',
    category: 'Financial',
    tags: ['loan', 'financial', 'credit'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'lender-name', 
        type: 'text', 
        label: 'Lender Name', 
        required: true, 
        x: 100, 
        y: 150, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 150 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'borrower-name', 
        type: 'text', 
        label: 'Borrower Name', 
        required: true, 
        x: 100, 
        y: 190, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 190 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'loan-amount', 
        type: 'text', 
        label: 'Loan Amount', 
        required: true, 
        x: 100, 
        y: 230, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 230 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'interest-rate', 
        type: 'text', 
        label: 'Interest Rate (%)', 
        required: true, 
        x: 270, 
        y: 230, 
        width: 120, 
        height: 30,
        position: { x: 270, y: 230 },
        size: { width: 120, height: 30 },
        page: 1
      },
      { 
        id: 'repayment-period', 
        type: 'text', 
        label: 'Repayment Period', 
        required: true, 
        x: 100, 
        y: 270, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 270 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'due-date', 
        type: 'date', 
        label: 'Due Date', 
        required: true, 
        x: 270, 
        y: 270, 
        width: 150, 
        height: 30,
        position: { x: 270, y: 270 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'lender-signature', 
        type: 'signature', 
        label: 'Lender Signature', 
        required: true, 
        x: 100, 
        y: 370, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 370 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'lender'
      },
      { 
        id: 'borrower-signature', 
        type: 'signature', 
        label: 'Borrower Signature', 
        required: true, 
        x: 350, 
        y: 370, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 370 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'borrower'
      }
    ],
    signers: [
      { id: 'lender', name: 'Lender', email: '', role: 'lender', order: 1, status: 'pending' },
      { id: 'borrower', name: 'Borrower', email: '', role: 'borrower', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-board-resolution',
    name: 'Board Resolution',
    description: 'Corporate board resolution for company decisions and approvals',
    category: 'Corporate Governance',
    tags: ['board', 'resolution', 'corporate', 'governance'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'company-name', 
        type: 'text', 
        label: 'Company Name', 
        required: true, 
        x: 100, 
        y: 150, 
        width: 300, 
        height: 30,
        position: { x: 100, y: 150 },
        size: { width: 300, height: 30 },
        page: 1
      },
      { 
        id: 'meeting-date', 
        type: 'date', 
        label: 'Meeting Date', 
        required: true, 
        x: 100, 
        y: 190, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 190 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'resolution-title', 
        type: 'text', 
        label: 'Resolution Title', 
        required: true, 
        x: 100, 
        y: 230, 
        width: 350, 
        height: 30,
        position: { x: 100, y: 230 },
        size: { width: 350, height: 30 },
        page: 1
      },
      { 
        id: 'resolution-details', 
        type: 'text', 
        label: 'Resolution Details', 
        required: true, 
        x: 100, 
        y: 270, 
        width: 400, 
        height: 60,
        position: { x: 100, y: 270 },
        size: { width: 400, height: 60 },
        page: 1
      },
      { 
        id: 'chairman-name', 
        type: 'text', 
        label: 'Chairman Name', 
        required: true, 
        x: 100, 
        y: 350, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 350 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'secretary-name', 
        type: 'text', 
        label: 'Secretary Name', 
        required: true, 
        x: 320, 
        y: 350, 
        width: 200, 
        height: 30,
        position: { x: 320, y: 350 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'chairman-signature', 
        type: 'signature', 
        label: 'Chairman Signature', 
        required: true, 
        x: 100, 
        y: 420, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 420 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'chairman'
      },
      { 
        id: 'secretary-signature', 
        type: 'signature', 
        label: 'Secretary Signature', 
        required: true, 
        x: 350, 
        y: 420, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 420 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'secretary'
      }
    ],
    signers: [
      { id: 'chairman', name: 'Chairman', email: '', role: 'chairman', order: 1, status: 'pending' },
      { id: 'secretary', name: 'Secretary', email: '', role: 'secretary', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-licensing-agreement',
    name: 'Licensing Agreement',
    description: 'Intellectual property licensing agreement for software, patents, or trademarks',
    category: 'Intellectual Property',
    tags: ['licensing', 'intellectual property', 'software', 'patents'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'licensor-name', 
        type: 'text', 
        label: 'Licensor Name', 
        required: true, 
        x: 100, 
        y: 150, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 150 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'licensee-name', 
        type: 'text', 
        label: 'Licensee Name', 
        required: true, 
        x: 100, 
        y: 190, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 190 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'licensed-property', 
        type: 'text', 
        label: 'Licensed Property/Technology', 
        required: true, 
        x: 100, 
        y: 230, 
        width: 350, 
        height: 30,
        position: { x: 100, y: 230 },
        size: { width: 350, height: 30 },
        page: 1
      },
      { 
        id: 'license-fee', 
        type: 'text', 
        label: 'License Fee', 
        required: true, 
        x: 100, 
        y: 270, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 270 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'royalty-rate', 
        type: 'text', 
        label: 'Royalty Rate (%)', 
        required: true, 
        x: 270, 
        y: 270, 
        width: 120, 
        height: 30,
        position: { x: 270, y: 270 },
        size: { width: 120, height: 30 },
        page: 1
      },
      { 
        id: 'license-term', 
        type: 'text', 
        label: 'License Term', 
        required: true, 
        x: 100, 
        y: 310, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 310 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'territory', 
        type: 'text', 
        label: 'Territory/Region', 
        required: true, 
        x: 270, 
        y: 310, 
        width: 180, 
        height: 30,
        position: { x: 270, y: 310 },
        size: { width: 180, height: 30 },
        page: 1
      },
      { 
        id: 'licensor-signature', 
        type: 'signature', 
        label: 'Licensor Signature', 
        required: true, 
        x: 100, 
        y: 400, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 400 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'licensor'
      },
      { 
        id: 'licensee-signature', 
        type: 'signature', 
        label: 'Licensee Signature', 
        required: true, 
        x: 350, 
        y: 400, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 400 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'licensee'
      }
    ],
    signers: [
      { id: 'licensor', name: 'Licensor', email: '', role: 'licensor', order: 1, status: 'pending' },
      { id: 'licensee', name: 'Licensee', email: '', role: 'licensee', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-shareholder-agreement',
    name: 'Shareholder Agreement',
    description: 'Agreement between company shareholders defining rights and obligations',
    category: 'Corporate Governance',
    tags: ['shareholder', 'equity', 'corporate', 'governance'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'company-name', 
        type: 'text', 
        label: 'Company Name', 
        required: true, 
        x: 100, 
        y: 140, 
        width: 300, 
        height: 30,
        position: { x: 100, y: 140 },
        size: { width: 300, height: 30 },
        page: 1
      },
      { 
        id: 'shareholder1-name', 
        type: 'text', 
        label: 'Shareholder 1 Name', 
        required: true, 
        x: 100, 
        y: 180, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 180 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'shareholder1-shares', 
        type: 'text', 
        label: 'Shareholder 1 Shares', 
        required: true, 
        x: 320, 
        y: 180, 
        width: 120, 
        height: 30,
        position: { x: 320, y: 180 },
        size: { width: 120, height: 30 },
        page: 1
      },
      { 
        id: 'shareholder2-name', 
        type: 'text', 
        label: 'Shareholder 2 Name', 
        required: true, 
        x: 100, 
        y: 220, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 220 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'shareholder2-shares', 
        type: 'text', 
        label: 'Shareholder 2 Shares', 
        required: true, 
        x: 320, 
        y: 220, 
        width: 120, 
        height: 30,
        position: { x: 320, y: 220 },
        size: { width: 120, height: 30 },
        page: 1
      },
      { 
        id: 'share-price', 
        type: 'text', 
        label: 'Share Price', 
        required: true, 
        x: 100, 
        y: 260, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 260 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'agreement-date', 
        type: 'date', 
        label: 'Agreement Date', 
        required: true, 
        x: 270, 
        y: 260, 
        width: 150, 
        height: 30,
        position: { x: 270, y: 260 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'shareholder1-signature', 
        type: 'signature', 
        label: 'Shareholder 1 Signature', 
        required: true, 
        x: 100, 
        y: 350, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 350 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'shareholder1'
      },
      { 
        id: 'shareholder2-signature', 
        type: 'signature', 
        label: 'Shareholder 2 Signature', 
        required: true, 
        x: 350, 
        y: 350, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 350 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'shareholder2'
      }
    ],
    signers: [
      { id: 'shareholder1', name: 'Shareholder 1', email: '', role: 'shareholder', order: 1, status: 'pending' },
      { id: 'shareholder2', name: 'Shareholder 2', email: '', role: 'shareholder', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-franchise-agreement',
    name: 'Franchise Agreement',
    description: 'Comprehensive franchise agreement for business expansion and brand licensing',
    category: 'Business Development',
    tags: ['franchise', 'business', 'expansion', 'licensing'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'franchisor-name', 
        type: 'text', 
        label: 'Franchisor Name', 
        required: true, 
        x: 100, 
        y: 140, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 140 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'franchisee-name', 
        type: 'text', 
        label: 'Franchisee Name', 
        required: true, 
        x: 100, 
        y: 180, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 180 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'franchise-brand', 
        type: 'text', 
        label: 'Franchise Brand/Name', 
        required: true, 
        x: 100, 
        y: 220, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 220 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'territory', 
        type: 'text', 
        label: 'Franchise Territory', 
        required: true, 
        x: 100, 
        y: 260, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 260 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'franchise-fee', 
        type: 'text', 
        label: 'Initial Franchise Fee', 
        required: true, 
        x: 100, 
        y: 300, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 300 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'royalty-rate', 
        type: 'text', 
        label: 'Royalty Rate (%)', 
        required: true, 
        x: 270, 
        y: 300, 
        width: 120, 
        height: 30,
        position: { x: 270, y: 300 },
        size: { width: 120, height: 30 },
        page: 1
      },
      { 
        id: 'franchise-term', 
        type: 'text', 
        label: 'Franchise Term (Years)', 
        required: true, 
        x: 400, 
        y: 300, 
        width: 100, 
        height: 30,
        position: { x: 400, y: 300 },
        size: { width: 100, height: 30 },
        page: 1
      },
      { 
        id: 'franchisor-signature', 
        type: 'signature', 
        label: 'Franchisor Signature', 
        required: true, 
        x: 100, 
        y: 400, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 400 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'franchisor'
      },
      { 
        id: 'franchisee-signature', 
        type: 'signature', 
        label: 'Franchisee Signature', 
        required: true, 
        x: 350, 
        y: 400, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 400 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'franchisee'
      }
    ],
    signers: [
      { id: 'franchisor', name: 'Franchisor', email: '', role: 'franchisor', order: 1, status: 'pending' },
      { id: 'franchisee', name: 'Franchisee', email: '', role: 'franchisee', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-distribution-agreement',
    name: 'Distribution Agreement',
    description: 'Product distribution agreement for wholesale and retail partnerships',
    category: 'Sales & Distribution',
    tags: ['distribution', 'wholesale', 'retail', 'sales'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'manufacturer-name', 
        type: 'text', 
        label: 'Manufacturer/Supplier', 
        required: true, 
        x: 100, 
        y: 150, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 150 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'distributor-name', 
        type: 'text', 
        label: 'Distributor Name', 
        required: true, 
        x: 100, 
        y: 190, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 190 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'products-description', 
        type: 'text', 
        label: 'Products Description', 
        required: true, 
        x: 100, 
        y: 230, 
        width: 350, 
        height: 30,
        position: { x: 100, y: 230 },
        size: { width: 350, height: 30 },
        page: 1
      },
      { 
        id: 'territory', 
        type: 'text', 
        label: 'Distribution Territory', 
        required: true, 
        x: 100, 
        y: 270, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 270 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'minimum-orders', 
        type: 'text', 
        label: 'Minimum Order Quantity', 
        required: true, 
        x: 100, 
        y: 310, 
        width: 180, 
        height: 30,
        position: { x: 100, y: 310 },
        size: { width: 180, height: 30 },
        page: 1
      },
      { 
        id: 'commission-rate', 
        type: 'text', 
        label: 'Commission Rate (%)', 
        required: true, 
        x: 300, 
        y: 310, 
        width: 150, 
        height: 30,
        position: { x: 300, y: 310 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'manufacturer-signature', 
        type: 'signature', 
        label: 'Manufacturer Signature', 
        required: true, 
        x: 100, 
        y: 400, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 400 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'manufacturer'
      },
      { 
        id: 'distributor-signature', 
        type: 'signature', 
        label: 'Distributor Signature', 
        required: true, 
        x: 350, 
        y: 400, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 400 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'distributor'
      }
    ],
    signers: [
      { id: 'manufacturer', name: 'Manufacturer', email: '', role: 'manufacturer', order: 1, status: 'pending' },
      { id: 'distributor', name: 'Distributor', email: '', role: 'distributor', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-merger-agreement',
    name: 'Merger & Acquisition Agreement',
    description: 'Corporate merger and acquisition agreement with terms and conditions',
    category: 'Mergers & Acquisitions',
    tags: ['merger', 'acquisition', 'corporate', 'due diligence'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'acquiring-company', 
        type: 'text', 
        label: 'Acquiring Company', 
        required: true, 
        x: 100, 
        y: 140, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 140 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'target-company', 
        type: 'text', 
        label: 'Target Company', 
        required: true, 
        x: 100, 
        y: 180, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 180 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'acquisition-price', 
        type: 'text', 
        label: 'Acquisition Price', 
        required: true, 
        x: 100, 
        y: 220, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 220 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'closing-date', 
        type: 'date', 
        label: 'Expected Closing Date', 
        required: true, 
        x: 320, 
        y: 220, 
        width: 150, 
        height: 30,
        position: { x: 320, y: 220 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'payment-method', 
        type: 'text', 
        label: 'Payment Method', 
        required: true, 
        x: 100, 
        y: 260, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 260 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'due-diligence-period', 
        type: 'text', 
        label: 'Due Diligence Period', 
        required: true, 
        x: 320, 
        y: 260, 
        width: 150, 
        height: 30,
        position: { x: 320, y: 260 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'acquiring-signature', 
        type: 'signature', 
        label: 'Acquiring Company Signature', 
        required: true, 
        x: 100, 
        y: 350, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 350 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'acquiring'
      },
      { 
        id: 'target-signature', 
        type: 'signature', 
        label: 'Target Company Signature', 
        required: true, 
        x: 350, 
        y: 350, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 350 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'target'
      }
    ],
    signers: [
      { id: 'acquiring', name: 'Acquiring Company', email: '', role: 'buyer', order: 1, status: 'pending' },
      { id: 'target', name: 'Target Company', email: '', role: 'seller', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-joint-venture',
    name: 'Joint Venture Agreement',
    description: 'Strategic joint venture agreement for collaborative business ventures',
    category: 'Strategic Partnerships',
    tags: ['joint venture', 'partnership', 'collaboration', 'strategic'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'party1-company', 
        type: 'text', 
        label: 'Party 1 Company', 
        required: true, 
        x: 100, 
        y: 140, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 140 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'party2-company', 
        type: 'text', 
        label: 'Party 2 Company', 
        required: true, 
        x: 100, 
        y: 180, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 180 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'venture-name', 
        type: 'text', 
        label: 'Joint Venture Name', 
        required: true, 
        x: 100, 
        y: 220, 
        width: 300, 
        height: 30,
        position: { x: 100, y: 220 },
        size: { width: 300, height: 30 },
        page: 1
      },
      { 
        id: 'venture-purpose', 
        type: 'text', 
        label: 'Business Purpose', 
        required: true, 
        x: 100, 
        y: 260, 
        width: 350, 
        height: 30,
        position: { x: 100, y: 260 },
        size: { width: 350, height: 30 },
        page: 1
      },
      { 
        id: 'party1-contribution', 
        type: 'text', 
        label: 'Party 1 Contribution (%)', 
        required: true, 
        x: 100, 
        y: 300, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 300 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'party2-contribution', 
        type: 'text', 
        label: 'Party 2 Contribution (%)', 
        required: true, 
        x: 270, 
        y: 300, 
        width: 150, 
        height: 30,
        position: { x: 270, y: 300 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'venture-duration', 
        type: 'text', 
        label: 'Venture Duration', 
        required: true, 
        x: 100, 
        y: 340, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 340 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'party1-signature', 
        type: 'signature', 
        label: 'Party 1 Signature', 
        required: true, 
        x: 100, 
        y: 420, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 420 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'party1'
      },
      { 
        id: 'party2-signature', 
        type: 'signature', 
        label: 'Party 2 Signature', 
        required: true, 
        x: 350, 
        y: 420, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 420 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'party2'
      }
    ],
    signers: [
      { id: 'party1', name: 'Party 1', email: '', role: 'partner', order: 1, status: 'pending' },
      { id: 'party2', name: 'Party 2', email: '', role: 'partner', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-insurance-claim',
    name: 'Insurance Claim Form',
    description: 'Comprehensive insurance claim form for property, liability, and business claims',
    category: 'Insurance',
    tags: ['insurance', 'claim', 'coverage', 'risk management'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'policyholder-name', 
        type: 'text', 
        label: 'Policyholder Name', 
        required: true, 
        x: 100, 
        y: 140, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 140 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'policy-number', 
        type: 'text', 
        label: 'Policy Number', 
        required: true, 
        x: 100, 
        y: 180, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 180 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'incident-date', 
        type: 'date', 
        label: 'Date of Incident', 
        required: true, 
        x: 320, 
        y: 180, 
        width: 150, 
        height: 30,
        position: { x: 320, y: 180 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'claim-type', 
        type: 'text', 
        label: 'Type of Claim', 
        required: true, 
        x: 100, 
        y: 220, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 220 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'incident-description', 
        type: 'text', 
        label: 'Incident Description', 
        required: true, 
        x: 100, 
        y: 260, 
        width: 400, 
        height: 60,
        position: { x: 100, y: 260 },
        size: { width: 400, height: 60 },
        page: 1
      },
      { 
        id: 'estimated-damage', 
        type: 'text', 
        label: 'Estimated Damage Amount', 
        required: true, 
        x: 100, 
        y: 340, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 340 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'contact-phone', 
        type: 'text', 
        label: 'Contact Phone', 
        required: true, 
        x: 320, 
        y: 340, 
        width: 150, 
        height: 30,
        position: { x: 320, y: 340 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'claimant-signature', 
        type: 'signature', 
        label: 'Claimant Signature', 
        required: true, 
        x: 100, 
        y: 420, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 420 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'claimant'
      },
      { 
        id: 'claim-date', 
        type: 'date', 
        label: 'Claim Submission Date', 
        required: true, 
        x: 350, 
        y: 450, 
        width: 150, 
        height: 30,
        position: { x: 350, y: 450 },
        size: { width: 150, height: 30 },
        page: 1
      }
    ],
    signers: [
      { id: 'claimant', name: 'Claimant', email: '', role: 'claimant', order: 1, status: 'pending' },
      { id: 'adjuster', name: 'Insurance Adjuster', email: '', role: 'adjuster', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-audit-report',
    name: 'Internal Audit Report',
    description: 'Comprehensive internal audit report template for financial and operational audits',
    category: 'Audit & Compliance',
    tags: ['audit', 'compliance', 'financial', 'risk assessment'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'company-name', 
        type: 'text', 
        label: 'Company Name', 
        required: true, 
        x: 100, 
        y: 140, 
        width: 300, 
        height: 30,
        position: { x: 100, y: 140 },
        size: { width: 300, height: 30 },
        page: 1
      },
      { 
        id: 'audit-period', 
        type: 'text', 
        label: 'Audit Period', 
        required: true, 
        x: 100, 
        y: 180, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 180 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'audit-date', 
        type: 'date', 
        label: 'Audit Completion Date', 
        required: true, 
        x: 320, 
        y: 180, 
        width: 150, 
        height: 30,
        position: { x: 320, y: 180 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'audit-scope', 
        type: 'text', 
        label: 'Audit Scope', 
        required: true, 
        x: 100, 
        y: 220, 
        width: 350, 
        height: 30,
        position: { x: 100, y: 220 },
        size: { width: 350, height: 30 },
        page: 1
      },
      { 
        id: 'key-findings', 
        type: 'text', 
        label: 'Key Findings', 
        required: true, 
        x: 100, 
        y: 260, 
        width: 400, 
        height: 60,
        position: { x: 100, y: 260 },
        size: { width: 400, height: 60 },
        page: 1
      },
      { 
        id: 'recommendations', 
        type: 'text', 
        label: 'Recommendations', 
        required: true, 
        x: 100, 
        y: 340, 
        width: 400, 
        height: 60,
        position: { x: 100, y: 340 },
        size: { width: 400, height: 60 },
        page: 1
      },
      { 
        id: 'auditor-name', 
        type: 'text', 
        label: 'Lead Auditor Name', 
        required: true, 
        x: 100, 
        y: 420, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 420 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'auditor-signature', 
        type: 'signature', 
        label: 'Lead Auditor Signature', 
        required: true, 
        x: 100, 
        y: 470, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 470 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'auditor'
      },
      { 
        id: 'management-signature', 
        type: 'signature', 
        label: 'Management Signature', 
        required: true, 
        x: 350, 
        y: 470, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 470 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'management'
      }
    ],
    signers: [
      { id: 'auditor', name: 'Lead Auditor', email: '', role: 'auditor', order: 1, status: 'pending' },
      { id: 'management', name: 'Management', email: '', role: 'management', order: 2, status: 'pending' }
    ],
    content: ''
  },
  {
    id: 'template-compliance-certificate',
    name: 'Compliance Certificate',
    description: 'Regulatory compliance certificate for industry standards and legal requirements',
    category: 'Compliance & Certification',
    tags: ['compliance', 'certification', 'regulatory', 'standards'],
    createdAt: new Date(),
    updatedAt: new Date(),
    usageCount: 0,
    fields: [
      { 
        id: 'certificate-title', 
        type: 'text', 
        label: 'Certificate Title', 
        required: true, 
        x: 100, 
        y: 120, 
        width: 350, 
        height: 30,
        position: { x: 100, y: 120 },
        size: { width: 350, height: 30 },
        page: 1
      },
      { 
        id: 'company-name', 
        type: 'text', 
        label: 'Company Name', 
        required: true, 
        x: 100, 
        y: 160, 
        width: 300, 
        height: 30,
        position: { x: 100, y: 160 },
        size: { width: 300, height: 30 },
        page: 1
      },
      { 
        id: 'compliance-standard', 
        type: 'text', 
        label: 'Compliance Standard/Regulation', 
        required: true, 
        x: 100, 
        y: 200, 
        width: 350, 
        height: 30,
        position: { x: 100, y: 200 },
        size: { width: 350, height: 30 },
        page: 1
      },
      { 
        id: 'assessment-date', 
        type: 'date', 
        label: 'Assessment Date', 
        required: true, 
        x: 100, 
        y: 240, 
        width: 150, 
        height: 30,
        position: { x: 100, y: 240 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'expiry-date', 
        type: 'date', 
        label: 'Certificate Expiry Date', 
        required: true, 
        x: 270, 
        y: 240, 
        width: 150, 
        height: 30,
        position: { x: 270, y: 240 },
        size: { width: 150, height: 30 },
        page: 1
      },
      { 
        id: 'certificate-number', 
        type: 'text', 
        label: 'Certificate Number', 
        required: true, 
        x: 100, 
        y: 280, 
        width: 200, 
        height: 30,
        position: { x: 100, y: 280 },
        size: { width: 200, height: 30 },
        page: 1
      },
      { 
        id: 'compliance-statement', 
        type: 'text', 
        label: 'Compliance Statement', 
        required: true, 
        x: 100, 
        y: 320, 
        width: 400, 
        height: 60,
        position: { x: 100, y: 320 },
        size: { width: 400, height: 60 },
        page: 1
      },
      { 
        id: 'certifying-authority', 
        type: 'text', 
        label: 'Certifying Authority', 
        required: true, 
        x: 100, 
        y: 400, 
        width: 250, 
        height: 30,
        position: { x: 100, y: 400 },
        size: { width: 250, height: 30 },
        page: 1
      },
      { 
        id: 'authority-signature', 
        type: 'signature', 
        label: 'Authority Signature', 
        required: true, 
        x: 100, 
        y: 450, 
        width: 200, 
        height: 60,
        position: { x: 100, y: 450 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'authority'
      },
      { 
        id: 'company-signature', 
        type: 'signature', 
        label: 'Company Representative Signature', 
        required: true, 
        x: 350, 
        y: 450, 
        width: 200, 
        height: 60,
        position: { x: 350, y: 450 },
        size: { width: 200, height: 60 },
        page: 1,
        signerId: 'company'
      }
    ],
    signers: [
      { id: 'authority', name: 'Certifying Authority', email: '', role: 'authority', order: 1, status: 'pending' },
      { id: 'company', name: 'Company Representative', email: '', role: 'company', order: 2, status: 'pending' }
    ],
    content: ''
  }
];
